### ISSUE TITLE
Can't find model 'en'

### ISSUE THREAD

**Issue by alx-xlx** [woolz/Text-Rewrite-NLP#3]
```sh
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from text_rewrite import TextRewrite
  File "/home/ubuntu/Text-Rewrite-NLP/text_rewrite.py", line 7, in <module>
    from best_syn import *
  File "/home/ubuntu/Text-Rewrite-NLP/best_syn.py", line 10, in <module>
    nlp = spacy.load('en')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/spacy/util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by alx-xlx** [comment]
I found this :
![chrome_8L3C8Mx7VU](https://user-images.githubusercontent.com/42188371/94359043-19f4a780-00a5-11eb-8b07-0f5100c2fe30.png)

SO i went ahead a replaced `nlp = spacy.load('en')` with `nlp = spacy.load('en_core_web_sm')`

Now I get this



Can someone reflect whats going on here
![wXEMXOAAJJ](https://user-images.githubusercontent.com/42188371/94359073-3d1f5700-00a5-11eb-9804-ab917642c6f8.png)

**Comment by chranga** [comment]
You can supress the warnings as described [here](https://spacy.io/usage/v3-1#warnings)
```
import warnings
warnings.filterwarnings("ignore", message=r"\[W007\]", category=UserWarning)
```

Also in best_syn.py
Use `nlp = spacy.load('en_core_web_trf')` instead of `nlp = spacy.load('en_core_web_sm')`

There are of course a number of reasons why you get that error. Some of which are discussed [on this thread](https://stackoverflow.com/questions/55921104/spacy-similarity-warning-evaluating-doc-similarity-based-on-empty-vectors)
